### PR TITLE
18: Upgrade runner to meet version 2 spec

### LINKED ISSUE #18: Upgrade to version 2 spec
If possible, this test runner should be updated to version 2 of the [test runner interface specification](https://github.com/exercism/docs/blob/main/building/tooling/test-runners/interface.md).

The version 2 spec differs from version 1 in that the `results.json` file contains detailed information on individual tests.
This information includes things like:

- The test status (passing/failing)
- The error message (if failing)
- The test code that was used to run the test

You are completely free on how you want to extract the test code, either via the AST or via finding the test code in the source code text via string manipulation. 

Let me know if there are any questions.

### PR DESCRIPTION
**Pull request by cdimitroulas**
Closes #18 

The solution here relies on a custom `hspec` formatter which deals with producing the `results.json` file. In order to make this work, it uses code injection to modify the exercise test code to use this custom formatter.

#### Outstanding items
- At the moment, the new `bin/run.sh` executes this code injection by using `stack runghc`. We may wish to avoid this by building an executable and executing that directly.

### CODE REVIEW

File: bin/run-tests.sh [hunk 1]
```diff
@@ -21,7 +21,7 @@ for test_dir in tests/*; do
     test_dir_path=$(realpath "${test_dir}")
     results_file_path="${test_dir_path}/results.json"
     expected_results_file_path="${test_dir_path}/expected_results.json"
-    stack_root=$(stack path --stack-root)
+    stack_root=$(stack --resolver lts-20.18 path --stack-root)
```
Comment (ErikSchierboom) [inline bin/run-tests.sh:24]: Is the resolved part required?

File: bin/run.sh [hunk 2]
```diff
@@ -37,6 +37,11 @@ file_contents=$(< "${input_dir}/stack.yaml")
 
 echo "system-ghc: true" >> "${input_dir}/stack.yaml"
 
+# Run our SetupTestFile which does some code injection to modify how the tests
+# will run to use our custom hspec formatter that outputs results.json automatically
+# TODO: see if we can avoid runghc and instead run a precompiled binary
```
Comment (ErikSchierboom) [inline bin/run.sh:42]: It would definitely be good if we could use a pre-compiled binary, as that would likely improve the speed.

File: bin/run.sh [hunk 3]
```diff
@@ -37,6 +37,11 @@ file_contents=$(< "${input_dir}/stack.yaml")
...
+stack --resolver lts-20.18 runghc src/SetupTestFile.hs $input_dir
```
Comment (ErikSchierboom) [inline bin/run.sh:43]: Similar to my above comment, is the `--resolver` part necessary?

File: bin/run.sh [hunk 4]
```diff
@@ -56,25 +61,23 @@ rm -rf .stack-work
 
 popd
 
-# Write the results.json file based on the exit code of the command that was 
-# just executed that tested the implementation file
-if [ $exit_code -eq 0 ]; then
-    jq -n '{version: 1, status: "pass"}' > ${results_file}
-else
+# If there is no existing results.json file it means that the tests failed to run
```
Comment (ErikSchierboom) [inline bin/run.sh:64]:
```suggestion
# If the results.json file does not exist, it means that the tests failed to run
```

File: tests/example-success/expected_results.json [hunk 5]
```diff
@@ -1,4 +1,52 @@
 {
-  "version": 1,
-  "status": "pass"
-}
+    "message": null,
+    "status": "fail",
```
Comment (ErikSchierboom) [inline tests/example-success/expected_results.json:3]: The status should be `pass`, as all tests are passing.

**Review by ErikSchierboom — COMMENTED** [review]
Great work! I've left some comments.

**Comment by ErikSchierboom** [comment]
@cdimitroulas You'll also need to fix the tests. You can run them locally by running: `./bin/run-tests-in-docker.sh`

File: tests/example-success/expected_results.json (hunk 5 above)
Comment (cdimitroulas) [reply tests/example-success/expected_results.json]: Good catch, sorry about that!

File: bin/run.sh (hunk 2 above)
Comment (cdimitroulas) [reply bin/run.sh:42]: I will see what I can do about this.
In the mean time, could you please approve the Github Actions workflow to run on the latest commits so that I can see whether the tests will pass there?

Comment (ErikSchierboom) [reply bin/run.sh:42]: Will do!

Comment (cdimitroulas) [reply bin/run.sh]: I think there might be an issue with the latest changes. Sorry about that. I've been switching between a Mac and Linux and the behaviour is completely different between the two even when using Docker which makes it kinda difficult to know if my changes are working or not.

I am currently debugging on my Linux machine to try and see what's going on there.

Comment (cdimitroulas) [reply bin/run.sh]: OK should be fixed now.

**Comment by ErikSchierboom** [comment]
Whilst testing things locally, I'm getting this error:

```
Error: [S-305]
Failed to generate a Cabal file using the Hpack library on file:
/mnt/exercism-iteration/package.yaml

The error encountered was:

/mnt/exercism-iteration/package.yaml: Error while parsing $.tests.test.dependencies[1] - invalid dependency "hspec      - aeson"
```

I submitted these files:

`src/LeapYear.hs`:

```haskell
module LeapYear (isLeapYear) where
 
isLeapYear :: Int -> Bool
isLeapYear year = hasFactor 4 && (not (hasFactor 100) || hasFactor 400)
  where hasFactor n = year `rem` n == 0
```

and 

`package.yaml`:

```yaml
name: leap

dependencies:
  - base

library:
  exposed-modules: LeapYear
  source-dirs: src

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - leap
      - hspec
```

One other request: could you make it such that after running `./bin/run-tests-in-docker.sh`, the original files are restored? Now I'm getting changed `package.yaml`, `HspecFormatter.hs` and `Tests.hs` files.

**Comment by cdimitroulas** [comment]
@ErikSchierboom I've added some automatic cleanup when running `bin/run-tests-in-docker.sh` or even `bin/run-tests.sh`.

Regarding the error you encountered, I can't reproduce that. I believe that this used to occur when you ran the test-runner multiple times without cleanup in-between because the lines appended to `package.yaml` would only work correctly once. I think [adding this newline char](https://github.com/exercism/haskell-test-runner/commit/2416867820bf04c39c8396c63be41a41ed66c2ee#diff-baaffd33afc7fcd5f874a28a4a5136f62d47227e92869f0d9c736bbe588aebcdL37) at the end of the code injection should have fixed the problem though.
Could you please try cleaning up the submitted input directory's `package.yaml` before running again?

Note that I presume this issue would not have occurred in a real run as the input directory would contain a clean copy of the files each time.

File: bin/cleanup-code-injections.sh [hunk 6]
```diff
@@ -0,0 +1,19 @@
...
+rm -f ./tests/example-all-fail/test/HspecFormatter.hs \
+  ./tests/example-empty-file/test/HspecFormatter.hs \
+  ./tests/example-partial-fail/test/HspecFormatter.hs \
+  ./tests/example-success/test/HspecFormatter.hs \
+  ./tests/example-syntax-error/test/HspecFormatter.hs
+  ./tests/example-all-fail/results.json \
+  ./tests/example-empty-file/results.json \
+  ./tests/example-partial-fail/results.json \
+  ./tests/example-success/results.json \
+  ./tests/example-syntax-error/results.json
```
Comment (ErikSchierboom) [inline bin/cleanup-code-injections.sh:12]: Maybe just add `HspecFormatter.hs` to the `.gitignore` file?

File: bin/cleanup-code-injections.sh [hunk 7]
```diff
@@ -0,0 +1,19 @@
...
+
+git checkout tests/example-all-fail/package.yaml tests/example-all-fail/test/Tests.hs \
```
Comment (ErikSchierboom) [inline bin/cleanup-code-injections.sh:14]: There is a small problem with this solution. What if I was to be modifying the `Tests.hs` or `package.yaml` files? E.g. for an upgrade or something. The changes would be reverted. What we usually do is to temporarily store the old files and then restore once the runner has finished.

**Review by ErikSchierboom — COMMENTED** [review]
There is a small problem with this solution. What if I was to be modifying the `Tests.hs` or `package.yaml` files? E.g. for an upgrade or something. The changes would be reverted. What we usually do is to temporarily

File: bin/cleanup-code-injections.sh (hunk 7 above)
Comment (cdimitroulas) [reply bin/cleanup-code-injections.sh:14]: OK, thanks. That sounds way better, I agree.

I will update to follow this approach 👍

File: bin/run.sh [hunk 8]
```diff
@@ -58,7 +60,12 @@ set +e
 # Run the tests for the provided implementation file and redirect stdout and
 # stderr to capture it
 test_output=$(stack build --resolver lts-20.18 --test --allow-different-user 2>&1)
-cp "${input_dir}/results.json" "${results_file}"
+
+# Copy results.json to the output directory (only if output directory is different from
+# the input directory)
+if [ "${input_dir}/results.json" != "${results_file}" ]; then
+  mv "${input_dir}/results.json" "${results_file}"
+fi
```
Comment (ErikSchierboom) [inline bin/run.sh:68]: Why this change?

Comment (cdimitroulas) [reply bin/run.sh:68]: The tests were failing for me when run with `bin/run-tests-in-docker.sh` or even `bin/run-tests.sh` because `cp` (or `mv`) throws an error saying `'tests/example-all-fail/results.json' and 'tests/example-all-fail/results.json' are the same file`.

This if statement guards against this case where the input_dir and output_dir are the same.

Comment (cdimitroulas) [reply bin/run.sh:68]: And without this `mv` command the file does not end up in the `output_dir` as the hspec formatter outputs it inside `input_dir`

**Comment by ErikSchierboom** [comment]
Let's go!
